### ISSUE TITLE
Could not connect to onenote

### ISSUE THREAD

**Issue by s44j4n** [stefankueng/EvImSync#1]
Hello,
Thanks for the great tool.
![image](https://user-images.githubusercontent.com/102669356/221378286-0d5aaeaf-cd21-4998-b20b-cbafe7379d4a.png)

I have followed instructions but keep getting this error. One note desktop is installed. I have tried enex files from both legacy evernote and evernote.

Cheers

**Comment by stefankueng** [comment]
try restarting the whole computer. Sometimes ON keeps running in a strange (stuck) way in the background.

**Comment by s44j4n** [comment]
Thanks Stefan,
All working well now.
