### ISSUE TITLE
Migration not completed

### ISSUE THREAD

**Issue by Kurtchen1a** [stefankueng/EvImSync#11]
Hi Stefan
- cannot complete migration
- I'm using the onenote desktop app
- the only thing which happens that a Evernote notebook is created in onenote - but no content

thx for your support! CU Peter

**Comment by stefankueng** [comment]
Sorry, but I have no idea what to do with your report.
Ok, so it doesn't work for you. I get that. Now what?

Do you get any error messages? What kind of notes do you import? Can you send me the enex file for testing?
Please provide any information which is actually useful. Telling me that it doesn't work is useless.

**Comment by Kurtchen1a** [comment]
Ok I got - my report was useless - so far so bad.

- no error messages
- I import notebooks - no single notes
- enex file: yes I can - see attachement
[ex_Sensi_Leader_EN.zip](https://github.com/stefankueng/EvImSync/files/11415342/ex_Sensi_Leader_EN.zip)

**Comment by stefankueng** [comment]
Thanks for the enex file. I tried it and it works just fine for me. All notes are imported including all attachments in them.
They're located in the new notebook named "ex_Sensi_Leader_EN", all in the section "not specified" 
![image](https://user-images.githubusercontent.com/665591/236690742-63f88603-dac5-4f00-8ab7-0d12fdeda2d4.png)

**Comment by Kurtchen1a** [comment]
Cool!
Thank you for your time&effort.
On my side it is still not working..
Could it be that the problem occurs with my OneNote desktop version? Should I try to update the existing version or could pls provide a link to a OneNote version with which it should work. Thanx again!

**Comment by stefankueng** [comment]
You have to use the desktop version of OneNote, not the one from the app store.
https://www.onenote.com/download

Maybe restarting the computer could help - I've seen it sometimes that a onenote process got stuck and then interfered with importing. 

If all that doesn't help, I'm out of ideas.

**Comment by Kurtchen1a** [comment]
Thanx - now its working!
