### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by Captnini** [stefankueng/EvImSync#12]
![image](https://user-images.githubusercontent.com/132943818/236909425-55a01ca1-e541-4cf2-a7c3-6cbe9af2533b.png)

**Comment by Captnini** [comment]
Please let me know the Fix for the above error.  I had no issues with my smaller notebooks (<7 notes).  It occurred when brining over 223 notes from one of my larger notebooks in Evernote.  Had to click 'OK' for most every note.

Thank you!

**Comment by stefankueng** [comment]
this looks like a stuck onenote process. Try rebooting your computer. Usually that fixes these kinds of issues.

**Comment by Captnini** [comment]
Thank you for the prompt reply!

Stay well!

**Comment by Captnini** [comment]
Worked perfectly!  Great too and thank you!
