### ISSUE TITLE
COM Exception

### ISSUE THREAD

**Issue by margosig** [stefankueng/EvImSync#13]
![COMException](https://github.com/stefankueng/EvImSync/assets/134086680/f2594219-d701-4754-9bb6-61dd9b23a724)

Repeated exceptions seen with large Notebook (11K docs).

Restarted to no avail.  Help.

**Comment by stefankueng** [comment]
please **read** the text in the message box. It tells you how you can help fix the problem.

**Comment by margosig** [comment]
My  bad.  Here are a few files (there were many files to choose from). 

[note-0ccfce23-d8e9-4128-a467-bc48db6cd9b0.zip](https://github.com/stefankueng/EvImSync/files/11519865/note-0ccfce23-d8e9-4128-a467-bc48db6cd9b0.zip)

**Comment by stefankueng** [comment]
Thanks!
It's fixed in Version 1.3.2

**Comment by margosig** [comment]
I ran 1.3.2 and received more errors.  Please find the failedNotes (before I forced an application exit) on today's run. Thank you.

[note-fe21bf45-62b5-4814-a039-ca97b424e7ec.zip](https://github.com/stefankueng/EvImSync/files/11522188/note-fe21bf45-62b5-4814-a039-ca97b424e7ec.zip)
