### ISSUE TITLE
Which OneNote account is used for importing?

### ISSUE THREAD

**Issue by jsetsaas** [stefankueng/EvImSync#17]
Hi,

I have imported several .ENEX files, and it seems to be randomly added to either my business Microsoft account, my personal Microsoft account, or on the local drive.

How do I chose where the notes are imported?

br
John Erik

**Comment by wongcc2012** [comment]
I hope this message not too late. I am new to this small program
My import way is to sign out all cloud service. Close all notebook and it seems will create a new notebook. Then I move or renane the notebook to cloud. And select the account I want

**Comment by wongcc2012** [comment]
just double checked, the import will create a notebook from your enex file name
