### ISSUE TITLE
ENEX files converted - not compatible with cloud notebook from Win 11

### ISSUE THREAD

**Issue by AFoztuh** [stefankueng/EvImSync#19]
Hello Stefan:

Thank you for making this convenient tool, and making it available for free.  I have Win 11 installed, and I am receiving an error message when converting the ENEX files for use by the Win 11 version of One Note: 

"We cannot open this section.  This notebook section was created in an older version of OneNote and are incompatible with your cloud notebook."  Windows' website suggest this error is (maybe) associated with error code 0xE40200AA.

Any suggestions?

Thank you, Andrew F.

**Comment by stefankueng** [comment]
make sure you don't have a notebook in onenote with the same name as the enex file you're trying to import.
Also, you should use the desktop version of onenote, not the one from the store.
