### ISSUE TITLE
RPC Server unavailable error 

### ISSUE THREAD

**Issue by leema101** [stefankueng/EvImSync#2]
Hi when I try use the app to import ENEX files I get this type of message - if I click OK the next note errors in the same way :-

Note: FW: Chat conversation 
System,lnvalidCastException: Unable to cast COM object of type
'Microsoft.Office.lnterop.OneNote.ApplicationClass• to interface type
This operation failed
because the Querylnterface call on the COM component for the
interface with IID '{452AC71A-B6SS4967-A208-A4CC39DD7949)' failed
due to the following error: The RPC server is unavailable. (Exception
from HRESULT: Ox8C0706BA),
at System. StubHelpers. StubHelpers.GetCOMlPFromRCW(Object
objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
at
Microsoft. Office. Interop. OneNote.lApplication. CreateNewPage(String
bstrSectionlD, String& pbstrPagelD, NewPageStyle npsNewPageStyle)
at
notesEvernote, String exportFile)

![image](https://user-images.githubusercontent.com/20333488/222108329-836b0914-4ac1-41ba-927f-a413d5edb38d.png)

**Comment by magste123** [comment]
I have the same issue. It seems to be when OneNote 365 is syncing the changes from the import, Onenote then crashes and the error pops up for all remaining notes. 

And for the notes that do get imported OneNote says as per the 2nd image.

![Screenshot 2023-04-07 165246](https://user-images.githubusercontent.com/48305852/230577402-42e57e2c-93ff-41f2-aef8-0bf79cbbf6e3.jpg)

![Screenshot 2023-04-07 164737](https://user-images.githubusercontent.com/48305852/230576439-f9359925-5cfa-424e-b362-9915f2c57928.jpg)
![Screenshot 2023-04-07 164951](https://user-images.githubusercontent.com/48305852/230576855-05f7a439-c3e9-4949-934c-07b454e9e90f.jpg)

**Comment by magste123** [comment]
The only events in the Windows log for the crash times I can see are types like  this one. I don't know if it is helpful or not.

![Screenshot 2023-04-07 172113](https://user-images.githubusercontent.com/48305852/230583276-c736fc50-0127-48a0-bbf7-3fcc1bf4c9b8.jpg)
![Screenshot 2023-04-07 172346](https://user-images.githubusercontent.com/48305852/230583420-e20dd399-d636-4bea-aa74-c2a02bd3255d.jpg)
[event log.zip](https://github.com/stefankueng/EvImSync/files/11177774/event.log.zip)

**Comment by pabutterworth** [comment]
Did anyone solve this? I'm having the same issue.
