### ISSUE TITLE
Will not convert ENEX files

### ISSUE THREAD

**Issue by peters248** [stefankueng/EvImSync#21]
Am getting the same error when trying to convert the latest version of Evernote to the latest desktop version of OneNote
![evernote2noenote error](https://github.com/stefankueng/EvImSync/assets/137645353/f2b2525a-764e-4076-8ab7-900f2938a1df)

No matter what I do, I get the attached error message for every Evernote note that's in the converting ENEX file.

**Comment by stefankueng** [comment]
With this error, usually a windows reboot helps.

**Comment by peters248** [comment]
Rebooting did not help.  I got the same error message (see attached).



------ Original Message ------
From "Stefan Küng" ***@***.***>
To "stefankueng/EvImSync" ***@***.***>
Cc "peters248" ***@***.***>; "Author" 
***@***.***>
Date 6/24/2023 10:58:49 AM
Subject Re: [stefankueng/EvImSync] Will not convert ENEX files (Issue 
#21)

**Comment by peters248** [comment]
Any other suggestions?

**Comment by songofruth** [comment]
I recently ran into this issue. Here's what I did - some of it may have been what helped:
1. Paused Syncing for OneDrive
2. Opened whichever version of OneNote this is: "C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE" (and kept it open during import)
3. Whenever OneNote indicated it was syncing, I cancelled the sync. (Note that you can also set syncing to manual, which might work as well)

When trying to import a notebook with over 200 notes, I kept encountering the issue seen above, at around note 12. Once I did the steps above, I had no problem importing the entire notebook. I haven't checked the notes to see whether they are muddled. But at least they are in.

Hope that helps.

**Comment by peters248** [comment]
songofruth: thanks for the suggestion but it didn't work. while there were no error messages, Evernote2Onenote only converted 19 of 245 Evernote notes to OneNote and it did this the three times I tried (deleting the OneNote file between attempts).
