### ISSUE TITLE
A modest suggestion

### ISSUE THREAD

**Issue by sapiomr** [stefankueng/EvImSync#22]
I was noticing that at least for me it seems like Notebooks in Endnote correspond more to sections in One Note. 

I just realized that you can multiselect the actual note parts of the note and just create a new notebook then a new section and move them into place. This might be a good suggestion to put as a note in your interface as initially I found it kind of confusing and then I figured it out.

**Comment by stefankueng** [comment]
> I was noticing that at least for me it seems like Notebooks in Endnote correspond more to sections in One Note.

it's documented here:
https://tools.stefankueng.com/Evernote2Onenote.html
see the info tip named "Evernote Tags"


> I just realized that you can multiselect the actual note parts of the note and just create a new notebook then a new section and move them into place. This might be a good suggestion to put as a note in your interface as initially I found it kind of confusing and then I figured it out.

That's a feature of Onenote and has nothing to do with the importer tool. Can't expect me to document Onenote as well.
