### ISSUE TITLE
Could not Connect to OneNote

### ISSUE THREAD

**Issue by malcolmsoreal** [stefankueng/EvImSync#23]
<img width="418" alt="Capture" src="https://github.com/stefankueng/EvImSync/assets/5827163/1839a6ac-6cac-41cf-8ce2-58c0584a833d">

Hi I am logged into my onenote poking around but I get this error even if I restart the program.

**Comment by summitcomputing** [comment]
I had the same problem - seems I was using OneNote for Windows 10, not OneNote Desktop. You can download the desktop version here: https://www.onenote.com/download
