### ISSUE TITLE
COMException error

### ISSUE THREAD

**Issue by venkatarangan** [stefankueng/EvImSync#26]
![Screenshot 2023-07-11 2236](https://github.com/stefankueng/EvImSync/assets/4814266/cbc099cc-8137-486f-8413-325a60409d6d)
Repo steps: I exported an evernote notebook with over 1235 notes, enex filesize of 720 MB, to OneNote running in Windows 11, connected to Office 365 account. It was stuck at 3 of 1235, when I cancelled the OneNote is syncing dialog. It then proceeded and throwed the attached error when it was 8 of 1235. Not sure what is going wrong here. Thanks.

**Comment by stefankueng** [comment]
please attach the failing note here.

**Comment by venkatarangan** [comment]
Here you go. The failing note is attached. Hope it helps in identifying the issue. 
[note-1f9bacff-5217-403f-9a94-671507cbafd4.zip](https://github.com/stefankueng/EvImSync/files/12025078/note-1f9bacff-5217-403f-9a94-671507cbafd4.zip)
