### ISSUE TITLE
location of embedded PDF changes / bulleted list with PDF

### ISSUE THREAD

**Issue by markuskhouri** [stefankueng/EvImSync#27]
The location of the attached / embedded PDFs (any document) is not preserved after a conversion.  Below is an example where, in EverNote, the PDFs are located in the second level list, but, after conversion, the PDFs are all located at the beginning of the note in OneNote.

Thinking that a picture might make this easier to understand...

1. This is what the note looked like in Evernote:
    1. ![image](https://github.com/stefankueng/EvImSync/assets/1365829/4201d787-bf1d-4606-9a22-bce248dea015)
2. This is what the note looked like in OneNote, after concerting it:
    1. ![image](https://github.com/stefankueng/EvImSync/assets/1365829/02454d73-9aa4-4a2b-9405-ff067fd3a390)
3. Here is the export from Evernote; I had to ZIP the file to be able to attach it.
    1. [_test.enex.zip](https://github.com/stefankueng/EvImSync/files/12023202/_test.enex.zip)
4. My environment:
     1. Windows 10, 22H2 (Build 19045.3086)
     3. Evernote: 10.58.8-win-ddl-public (4175); Editor: v172.19.3; Service: v1.69.5
     4. Microsoft® OneNote® for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20324) 64-bit 
     5. Evernote2Onenote-1.3.3

If additional information is needed, please do not hesitate to ask.

**Comment by stefankueng** [comment]
I don't think I can fix this:
onenote ignores both <embed> and <object> tags in html. So it's not possible to add files _inside_ a document. I can only add them at the end of the page, _after_ the html content from the evernote note.
And that's what is currently implemented.

**Comment by markuskhouri** [comment]
I do not understand your comment.  Below is a screenshot of a OneNote I created which has PDF documents in the middle of the note, using the bullet point approach similar to that in the original description.  

![image](https://github.com/stefankueng/EvImSync/assets/1365829/1ab57200-d576-4221-9694-6b687354120a)

Attached is the ZIP'ed export of the OneNote page, if it helps.

[Test of embedded attachments.zip](https://github.com/stefankueng/EvImSync/files/12137309/Test.of.embedded.attachments.zip)

**Comment by stefankueng** [comment]
I didn't say that ON can't do it. I said that Evernote2Onenote can't. At least not without a complete (and I really mean **complete** here) rewrite using a completely different import approach. And even that approach would not work because most of the info required is not documented by MS.

**Comment by markuskhouri** [comment]
Thanks for looking into this.
