### ISSUE TITLE
Import appears successful, but notes are empty

### ISSUE THREAD

**Issue by JormaJayZ** [stefankueng/EvImSync#3]
Hello,

used the Evernote Legacy app to export notes to ENEX files.
Running Windows 10 with .NET 4.8 and OneNote Desktop from O365, version 2212 from Monthly Enterprise Channel.

The import is really quick (both for a 2MB and a 20MB backup) and it creates a new notebook with lots of pages. Unfortunately, those pages are all empty.

As a sanity check, I tried importing the same files with the (no longer official) Microsoft OneNote Importer v1.1. A much slower process with a different outcome. It also creates notebook with pages. Unfortunately, the pages have not kept the names from Evernote but all simply show "Untitled page". The good thing though: those untitled pages actually have the content I was looking for.

So I was hoping that this is actually something fixable as the ENEX files seem to contain the relevant information.

Any ideas what might be causing the empty pages, and how to fix it? Happy to provide more details if necessary.

**Comment by stefankueng** [comment]
I would need an enex file that has notes in it that then show up empty in ON.
Maybe you can create such an enex file from your notes?

**Comment by neowillyCom** [comment]
Hi,
Same problem to me. The Enex file was imported to Obsidian with all text and files enclosed (pdfs and jpeg mainly). But when imported to OneNote365, they are empty... The files are there, but the text I wrote in Evernote no...
Any idea or solution?
Thanks a lot in advance!

**Comment by stefankueng** [comment]
As I said: I need an enex file to reproduce the problem.

**Comment by neowillyCom** [comment]
I´ve used also the Legacy version. But current version is not an option, as I have more than 10.000 notes on Evernote to move...
The question is why to move all the +10.000 notes to Obsidian the Legacy Evernote done well the job?

**Comment by stefankueng** [comment]
@neowillyCom what does the amount of notes have to do with whether the legacy or new version is used?
And I can't believe I'm saying this _again_, since it's clearly stated on the [website](https://tools.stefankueng.com/Evernote2Onenote.html): the legacy version **does not work**!

**Comment by JormaJayZ** [comment]
@neowillyCom I don't know details of any such limitation but I exported 986 notes (not 100) if that helps you somehow ;)

> And I can't believe I'm saying this again, since it's clearly stated on the [website](https://tools.stefankueng.com/Evernote2Onenote.html): the legacy version does not work!

Gruezi @stefankueng 

I support and agree that adding a brief note to your site about not using Legacy would avoid having to repeat it ;-)
But it's currently **not** on there and I was not aware of the "don't use legacy" - not from the website, and maybe even you missed it in my opening statement. 

![image](https://user-images.githubusercontent.com/112185470/227621160-d6a9d166-a3de-41f7-8587-068ed2250c62.png)

That being said:
Thanks for your support and clarifying!
