### ISSUE TITLE
Could not create target notebook in OneNote

### ISSUE THREAD

**Issue by schmusekater1959** [stefankueng/EvImSync#30]
I believe I followed all steps described. I have the latest OneNote app installed on my laptop from my O365 personal subscription. I downloaded the latest version for evernote2onenote (1.3.3) and unpacked it. When I run the tool, I get the messages stated in the subject line.

![image](https://github.com/stefankueng/EvImSync/assets/140358883/16ca9946-2a7f-4481-bcab-38e14a430ee1)

**Comment by PaulMpls** [comment]
I have the same issue with 1.3.5.234

![image](https://github.com/stefankueng/EvImSync/assets/145939625/fc3e7aee-4a06-418a-be92-69b31149443a)
