### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by Karmuk** [stefankueng/EvImSync#31]
I got an error message during my first import and it said to create a ticket.
I freshly installed Onenote because it did not work with the OneNote that was installed before

I think it is probably due to something in OneNote, because when I opened OneNote again I had to confirm some licensing popup (which did not show up when I opened the new OneNote the first time before the import) 
Then I closed OneNote and started the import again and it worked

[note-aa7c53fa-3079-4cd6-ab10-5f54e7dd06b0.zip](https://github.com/stefankueng/EvImSync/files/12207349/note-aa7c53fa-3079-4cd6-ab10-5f54e7dd06b0.zip)

**Comment by stefankueng** [comment]
thanks for the note, but it imports for me fine.
