### ISSUE TITLE
Evernote XML code will not import to onenote during import

### ISSUE THREAD

**Issue by wongcc2012** [stefankueng/EvImSync#35]
(source sample)
![image](https://github.com/stefankueng/EvImSync/assets/111074201/98ba2c92-eecf-4a5a-a730-ef2a58ac6798)

```
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
<settings pass="oobeSystem">
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="x86" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<AutoLogon>
<Password>
<PlainText>true</PlainText>
</Password>
<Username>Administrator</Username>
<Enabled>true</Enabled>
<LogonCount>1</LogonCount>
</AutoLogon>
<UserAccounts>
<AdministratorPassword>

```

(result) all open and close tag will not import. 
![image](https://github.com/stefankueng/EvImSync/assets/111074201/396a7236-2947-469e-acdf-24e6696a03ea)

Administrator
true
1
true
true
true

**Comment by stefankueng** [comment]
Sorry, no.
I would need the whole note here, not just screenshots.

**Comment by wongcc2012** [comment]
BELOW THE ENTIRE NOTE. I HAVE WRITTEN THE SYSPREP XML FOR MY REFRENCE. 


#Generic 32bit + 64 bit OS, SKIP OOBE, Auto logon, Random machine name


<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
<settings pass="oobeSystem">
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="x86" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<AutoLogon>
<Password>
<Value>Abcd1234!!</Value>
<PlainText>true</PlainText>
</Password>
<Username>Administrator</Username>
<Enabled>true</Enabled>
<LogonCount>1</LogonCount>
</AutoLogon>
<UserAccounts>
<AdministratorPassword>
<Value>Abcd1234!!</Value>
<PlainText>true</PlainText>
</AdministratorPassword>
</UserAccounts>
<OOBE>
<HideEULAPage>true</HideEULAPage>
<HideLocalAccountScreen>true</HideLocalAccountScreen>
<HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
<HideOnlineAccountScreens>true</HideOnlineAccountScreens>
<HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
<NetworkLocation>Home</NetworkLocation>
<ProtectYourPC>3</ProtectYourPC>
<SkipMachineOOBE>true</SkipMachineOOBE>
<SkipUserOOBE>true</SkipUserOOBE>
<UnattendEnableRetailDemo>false</UnattendEnableRetailDemo>
</OOBE>
</component>
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<AutoLogon>
<Password>
<Value>Abcd1234!!</Value>
<PlainText>true</PlainText>
</Password>
<Username>Administrator</Username>
<Enabled>true</Enabled>
<LogonCount>1</LogonCount>
</AutoLogon>
<UserAccounts>
<AdministratorPassword>
<Value>Abcd1234!!</Value>
<PlainText>true</PlainText>
</AdministratorPassword>
</UserAccounts>
<OOBE>
<HideEULAPage>true</HideEULAPage>
<HideLocalAccountScreen>true</HideLocalAccountScreen>
<HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
<HideOnlineAccountScreens>true</HideOnlineAccountScreens>
<HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
<NetworkLocation>Home</NetworkLocation>
<ProtectYourPC>3</ProtectYourPC>
<SkipMachineOOBE>true</SkipMachineOOBE>
<SkipUserOOBE>true</SkipUserOOBE>
<UnattendEnableRetailDemo>false</UnattendEnableRetailDemo>
</OOBE>
</component>
</settings>
</unattend>
---------------------------------------------------------------------------------------------------------------------------

**Comment by wongcc2012** [comment]
[TESTING_Poc-UATOnly.zip](https://github.com/stefankueng/EvImSync/files/12551012/TESTING_Poc-UATOnly.zip)
sp
[Uploading TESTING_Poc-UATOnly.7z…]()

sorry misunderstood. reuploaded.

**Comment by wongcc2012** [comment]
please let me know if anything I can help
