### ISSUE TITLE
Not able to pass that step

### ISSUE THREAD

**Issue by Tryingausername** [stefankueng/EvImSync#38]
![Screenshot 2023-09-16 085636](https://github.com/stefankueng/EvImSync/assets/145204767/1842e561-36bd-4114-bf59-93cb47ed2a05)

**Comment by Tryingausername** [comment]
Also tried on two different computers with office OneNote and all the latest updates and no luck.

**Comment by stefankueng** [comment]
click on "import enex file" button, select the enex file.
