### ISSUE TITLE
Failing on every note

### ISSUE THREAD

**Issue by pjb2600** [stefankueng/EvImSync#40]
Hi

I'm trying to report using the guide provided but have had to zip the files to enable it to up.

It gets as far as creating the notebook but it then fails, and notebook OneNote has crashed. I'm using the OneNote app downloaded as part of MS 365 subscription.

[ev2on.zip](https://github.com/stefankueng/EvImSync/files/12866419/ev2on.zip)

thanks

Peter

**Comment by stefankueng** [comment]
works fine for me. I could import every note.
