### ISSUE TITLE
Progresses through first few notes and then fails for every note after

### ISSUE THREAD

**Issue by Ubermensch7492** [stefankueng/EvImSync#41]
First, a huge thank you for creating this tool.  I'm importing ~12 notebooks.  Six worked well with no issues.  The other six seem to fail ~1/3 of the way through the notes.  Once the first note fails, every subsequent note fails to import.  I've attached the failure notes from one of the notebooks for reference.
[note-0a43bee9-2b7f-4825-829e-b8221d2e1111.zip](https://github.com/stefankueng/EvImSync/files/12905866/note-0a43bee9-2b7f-4825-829e-b8221d2e1111.zip)

**Comment by Ubermensch7492** [comment]
After reading a few other issue reports and recognizing the issue with syncing between OneNote and OneDrive, I managed to solve my problem.  My process was to have Onenote open and running and then to turn off all internet access (turned wifi off).  That forces Onenote to create a local copy of all files during the migration.  With this approach I was able to import notebooks as large as 1gb.  Once all of the notebooks were created locally (~5gb), I turned wifi back on and allowed Onenote and Onedrive to migrate the files to the cloud.  I hope this helps others, and thanks again for creating this great tool!

**Comment by simplified-life** [comment]
Thanks for this tip. I turned off my wifi connection and successfully imported. I did have to occasionally cancel an attempted sync from onenote as these were causing the import to pause. Once I went back online it did all get migrated to my personal onedrive account automatically.
