### ISSUE TITLE
fails multiple ways using legacy evernote

### ISSUE THREAD

**Issue by Psercom** [stefankueng/EvImSync#44]
works on some enex files then fails on others
com exception, different server errors and also invalidcastexception

then wanting to build source, doesn't build assemblyinfo.cs error 9009 calling gitwcrev

**Comment by stefankueng** [comment]
Ok, I'll fix some files and leave some others, and then catch some exceptions.

about your build failures: you have to build Evernote2Onenote, NOT EvImSync (it's in a subfolder).
