### ISSUE TITLE
Import error (note attached)

### ISSUE THREAD

**Issue by BrendanL79** [stefankueng/EvImSync#45]
Evernote2Onenote Version 1.3.5.234
When attempting to import this note from a larger .enex file, the error dialog says: (see screenshot)

![image](https://github.com/stefankueng/EvImSync/assets/428859/c5a6ad45-bbdc-4329-8cd8-e508267ebe19)

[note-e404341e-1ca4-4237-a336-b46aa18b202f.zip](https://github.com/stefankueng/EvImSync/files/13064577/note-e404341e-1ca4-4237-a336-b46aa18b202f.zip)

**Comment by johncolby** [comment]
Exact same error for me. Gets part way through the import, then the error window pops up and OneNote crashes.

[note-99bf61a4-fd39-461b-a20b-b4dfc509be46.txt](https://github.com/stefankueng/EvImSync/files/13074305/note-99bf61a4-fd39-461b-a20b-b4dfc509be46.txt)
