### ISSUE TITLE
Gets Stuck after Creating new Notebook

### ISSUE THREAD

**Issue by tynelson8** [stefankueng/EvImSync#46]
Hey Stefan! Thanks for all your work building this. 

I'm trying to import 100 notes. It finds the .enex file & creates a relevant notebook title, but can't import any of the notes. Any idea why? Images attached. Thanks!

![image](https://github.com/stefankueng/EvImSync/assets/131706044/ed1e0e38-c7b9-47b8-9d5e-8dbee1ddf314)
![image](https://github.com/stefankueng/EvImSync/assets/131706044/b24a058f-df54-43d9-9620-2e097a547436)

**Comment by tynelson8** [comment]
Now getting this error - any tips?
![image](https://github.com/stefankueng/EvImSync/assets/131706044/3c5f99fb-594f-4074-97dc-366c7b56ac0a)

**Comment by stefankueng** [comment]
the enex file is corrupt.
Hint: when exporting from evernote, make sure the export is really, really finished. Because the exporting is done in the background and you don't notice that it's still running...
