### ISSUE TITLE
Created notebooks can not be synced

### ISSUE THREAD

**Issue by mikerr** [stefankueng/EvImSync#56]
Just migrated all my evernote notebooks over, worked a treat with one problem:

All the notebooks refuse to sync, and even have "sync now" greyed out when I right click them.

I do have a workaround, but its not ideal:
My solution is to recreate a new notebook manually with same/similar name, 
and then drag the notes section into that new notebook. The new notebook will then sync fine.

**Comment by stefankueng** [comment]
https://support.microsoft.com/en-us/office/move-a-onenote-for-windows-notebook-that-you-ve-shared-with-others-56c7659e-1850-49a6-8874-e2db6b440cd4
https://support.microsoft.com/en-us/office/how-to-move-my-local-notebooks-to-onedrive-or-sharepoint-7343c424-cdee-4bbf-9245-312549e81fc0
