### ISSUE TITLE
doesn't work well

### ISSUE THREAD

**Issue by devzhuchuanbo** [stefankueng/EvImSync#6]
The window layout is wrong when opening, and an error was reported when importing into OneNote.
 I tried running it as admin and using compatibility mode, even installing an old version of Evernote (2016, 6.1), but it doesn't work.
<img width="293" alt="Snipaste_2023-03-29_15-44-24" src="https://user-images.githubusercontent.com/20489157/228463079-78ba484e-b5ad-4969-a40e-b439595b4194.png">
<img width="357" alt="Snipaste_2023-03-29_15-43-40" src="https://user-images.githubusercontent.com/20489157/228463139-5bd96da2-b715-4136-ab42-dc13ccb5dcd8.png">

**Comment by stefankueng** [comment]
you must install the desktop version from office. It does not work with the legacy app version of Onenote.

**Comment by Tryingausername** [comment]
Having the same issue with all requirements installed for onenote and other items
