### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by evanwolf** [stefankueng/EvImSync#8]
![image](https://user-images.githubusercontent.com/205622/232862374-7a112a76-7ad7-4b80-b7cd-1831f45aff38.png)
while running 
![image](https://user-images.githubusercontent.com/205622/232862648-d9f77893-4095-4b47-b8b1-0c8f6d4e9555.png)
on a large enex file (637 MB). 
Previously worked fine on small files.

**Comment by stefankueng** [comment]
please export only the note "Untitled Quick Note" in notebook "evanwolf's notebook", and attach it here if possible.
It seems that note is not properly formed.
